@startuml
autonumber
actor "Paciente / Cuidador" as User
participant "Agendador (Cron)" as Cron
participant "Monitoramento" as Mon
database "Firestore" as DB
participant "Notificação (FCM)" as FCM

Cron -> Mon: Executa a cada minuto
Mon -> DB: Busca pacientes e medicamentos
DB --> Mon: Retorna dados e datas de tomada

note over Mon: Calcula tempo da dose: \n(agora - proximaDose)

alt No Horário
    Mon -> FCM: Dispara "Hora do Remédio"
else Atraso > 10 min
    Mon -> FCM: Alerta "Medicamento Atrasado"
else Crítico > 30 min
    Mon -> FCM: Alerta Crítico "Não Confirmado"
end

FCM -> User: Envia Push Notification
Mon -> DB: Grava no Histórico do medicamento
